### ISSUE TITLE
License violation with ToS

### ISSUE THREAD

**Issue by mibofra** [zigazajc007/AdminGUI#1]
Hi!
I've seen your plugin just for curiosity. I've seen your ToS because it's big and pretty visble in the readme.

This are the four Free Software freedoms, that regards the GPLv3 too:

> - The freedom to run the program as you wish, for any purpose (freedom 0).
> - The freedom to study how the program works, and change it so it does your computing as you wish (freedom 1). Access to the source code is a precondition for this.
> - The freedom to redistribute copies so you can help your neighbor (freedom 2).
> - The freedom to distribute copies of your modified versions to others (freedom 3). By doing this you can give the whole community a chance to benefit from your changes. Access to the source code is a precondition for this.

from Wikipedia: https://en.wikipedia.org/wiki/The_Free_Software_Definition but you can check on the site of Free Software Foundation too.

So, do you think your ToS respect the license are you using? And no, you can't change the license to solve the issue, the GPLv3 is strict about this. In fact, you can see that you have 3 forks.

I ask because I don't understand the requests about not share or upload the plugin or not leak it. As for the GPLv3, everyone can share, reupload, modify and upload modified copies of your pluing, as mering back the modifications.

**Comment by zigazajc007** [comment]
Hello,

This TOS is only valid for Premium plugin which is on private github
repository. On this free version which is open source users can share,
reupload, modify and upload modified copies.

V V pet., 17. apr. 2020 ob 00:28 je oseba Francesco Bonanno <
notifications@github.com> napisala:

**Comment by mibofra** [comment]
Thanks for the clarificaiton. but: https://www.gnu.org/licenses/gpl-faq.html.en#DoesTheGPLRequireAvailabilityToPublic

So, I guess at least, the premium features of your plugins are licensed with another license, and if you reuse total of part of the code of the free version, that license is compatible without issues with the GPL... http://gplv3.fsf.org/wiki/index.php/Compatible_licenses

Surely, something only you and who bought the plugin know.
