### ISSUE TITLE
Adding Support for Bungeeecord

### ISSUE THREAD

**Issue by WaldperlachFabi** [zigazajc007/AdminGUI#3]
It would be great if you could add Bungeecord like if you ban someone he gets banned on every Server.

**Comment by zigazajc007** [comment]
Hello,

AdminGUI plugin does use existing ban system. For example, if you already have LiteBans installed it will use it to ban people. So in the LiteBans plugin, you can configure that. If you don't have any plugin installed to manage bans it will just use default one provided by Spigot.

Currently supported ban plugins:
- AdminBans
- AdvancedBans
- LiteBans
